version: '3.4'

services:
  whitenoise:
    image: whitenoise
    container_name: whitenoise
    build:
      context: .
      dockerfile: ./Dockerfile
    # environment:
    #   SONOS_API_IP: ${SONOS_API_IP}
    #   MQTT_HOST: ${MQTT_HOST}
    #   MQTT_PORT: ${MQTT_PORT}
    restart: always
    volumes:
      - type: bind
        source: ./config
        target: /app/config
